apiVersion: skaffold/v4beta5
kind: Config
metadata:
  name: <%= serviceName %>

build:
  artifacts:
    - image: <%= serviceName %>
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "app/**/*.py"
            dest: "/app"

deploy:
  helm:
    releases:
      - name: <%= serviceName %>
        chartPath: helm
        namespace: scholar-spark-dev
        createNamespace: true
        valuesFiles:
          - helm/values.yaml
        setValues:
          image.repository: <%= serviceName %>
          image.tag: latest

portForward:
  - resourceType: service
    resourceName: <%= serviceName %>
    namespace: scholar-spark-dev
    port: <%= port %>
    localPort: <%= port %>
