apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: { name }

build:
  artifacts:
    - image: { name }
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.py"
            dest: .
          - src: "app/**/*.py"
            dest: .

deploy:
  helm:
    releases:
      - name: { name }
        chartPath: helm
        valuesFiles:
          - helm/values.yaml
        setValues:
          image.repository: { name }
        setValueTemplates:
          image.tag: "{{.DIGEST}}"

portForward:
  - resourceType: service
    resourceName: { name }
    namespace: scholar-spark
    port: 8000
    localPort: 8000
